Color and Anchor Link Nav Style Updates
upbound/docs pull request #176
Opened 2023-07-21 20:46 UTC by shanecmiller23

- Update UI styling for right anchor list navigation
- Update purple colors used on Home page graphics and links

2023-07-21 22:41 UTC, julzvilla requested changes

2023-07-21 22:41 UTC, julzvilla commented on themes/upbound/assets/scss/_home.scss
> +                color: #7D4CD1 !important;
Nitpick: could you use the variable `$up-purple-400` here instead? just to keep things consistent and easier to update down the link

2023-07-21 23:02 UTC, shanecmiller23 commented
@julzvilla made that change

2023-07-24 14:52 UTC, julzvilla approved these changes
Looks good!

2023-07-24 19:37 UTC, shanecmiller23 commented
@julzvilla updated tables here too now

2023-07-24 22:47 UTC, merged