IP Addresses: publish IP Addresses for Upbound Infrastructure
upbound/docs pull request #262
Opened 2023-10-30 18:14 UTC by darkmuggle

Add page for Upbound infrastructure IP addresses.

2023-10-30 18:14 UTC, Upbound-CLA commented
[![CLA assistant check](https://cla.upbound.io/pull/badge/not_signed)](https://cla.upbound.io/upbound/docs?pullRequest=262) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.upbound.io/upbound/docs?pullRequest=262) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.upbound.io/check/upbound/docs?pullRequest=262) it.</sub>

2023-10-31 23:31 UTC, AlainRoy commented on content/reference/ipaddresses.md
> +Upbound Infrastructure uses the following egress addresses for hosted control
These are just the MCP egresses? What about from the main cluster for Librarian & the GitHub App?

I think we might need a slightly more detailed paragraph here. I'm running short on time, but I'll make a suggestion later if I have time. But I think that a reader who doesn't have all your context may have trouble understanding.

2023-11-01 02:57 UTC, AlainRoy commented on content/reference/ipaddresses.md
> +Upbound Infrastructure uses the following egress addresses for hosted control
Suggested text:

## Allowing access from Upbound 
Upbound makes outbound connections in three ways:
1. Connections to GitHub to copy the contents of a repository containing your Configuration
2. Connections to GitHub to create your Configurations repository with the Upbound GitHub App. 
3. Connections from Upbound Control Planes to your infrastructure. For example, if you use provider-kubernetes to configure a Kubernetes cluster, there will be a connection to your Kubernetes cluster. 

If you restrict the IP addresses that are allowed to communicate with GitHub or your infrastructure, you'll need to allow the Upbound IP addresses.

To allow access to Github, allow access to the following IP addresses:
* X.X.X.X
* Y.Y.Y.Y

To allow access to your infrastructure from a control plane, allow access to the following IP addresses:
* A.A.A.A
* B.B.B.B

2023-11-01 21:10 UTC, plumbis requested changes

2023-11-01 21:10 UTC, plumbis commented on content/reference/ipaddresses.md
> +list as infrastructure needs change.
```suggestion
{{< hint "note" >}}
Upbound reserves the right to change this
list of IP addresses.
{{< /hint >}}
```

2023-11-01 21:10 UTC, plumbis commented on content/reference/ipaddresses.md
> +## IP Addresses
```suggestion
```

2023-11-01 21:10 UTC, plumbis commented on content/reference/ipaddresses.md
> +- [Github](https://docs.github.com/en/enterprise-cloud@latest/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/managing-allowed-ip-addresses-for-your-or
```suggestion
```

I'd remove this block. If the user needs the IP list they likely already know how to whitelist the addresses.

2023-11-03 17:21 UTC, plumbis approved these changes

2023-12-06 20:16 UTC, merged