Spaces API Documentation Update
upbound/docs pull request #330
Opened 2024-03-06 02:47 UTC by tr0njavolta

This PR attempts to restructure the current spaces API reference documentation. Should more closely resemble the Crossplane API docs for readability and organization https://docs.crossplane.io/master/api/

To Do
- [ ] Make sure the structure of content in the yaml files is correct @haarchri - would be helpful to take a look.
- [ ] Color correction
- [ ] UI correction

2024-03-06 09:23 UTC, haarchri commented
for me the page looks empty 

![image](https://github.com/upbound/docs/assets/21083497/b3d2497d-036f-4595-8972-ba38201a31f1)

2024-03-06 15:36 UTC, plumbis requested changes
I added some suggestions to help fix the big problems- with those in place it looks pretty good! just need to fix some coloring around the object types and nudge spacing after more screen real estate is freed up with the grid fix.

2024-03-06 15:36 UTC, plumbis commented on themes/upbound/assets/scss/_color-mode-dark.scss
> +    --plus-svg: url("/img/plus-150.svg");
I think this needs to be `img/lightbox/...`, but these are only dark +/-. 

You can get the originals from here:
https://github.com/crossplane/docs/tree/master/themes/geekboot/static/img

Be sure to add the same vars into the `_color-mode-light.scss` file as well.

2024-03-06 15:36 UTC, plumbis commented on themes/upbound/assets/scss/_crds.scss
> +@mixin vertical-bar {
In order to expand the central display area over the column where the Table of Contents normally is you have to adjust the grid layout. My suggestion is something like:

1. Above this create a new class:
```css
.crd-grid {

  @include media-breakpoint-up(xl) {
  display: grid;
  grid-template-columns: 336px minmax(0,.98fr);
  grid-template-rows: 1fr auto;
  grid-template-areas:
  "left-sidebar-nav content-body right-sidebar-toc"
  "footer-container footer-container footer-container";
  }

}
```

2. Edit `themes/upbound/layouts/_default/baseof.html` and conditionally load the grid:
```diff


    {{ partial "body/top-nav" .}}
-    <div class="grid" data-bs-spy="scroll" data-bs-target="#TableOfContents">
+    <div class="{{ if eq $.Params.Product "crds" }}crd-grid{{else}} grid {{ end }} " data-bs-spy="scroll" data-bs-target="#TableOfContents">
      {{ partialCached "icons/sprites" . }}
      {{ partial "body/left-sidebar-nav" .}}

```

2024-03-06 17:25 UTC, tr0njavolta commented
#330 
Should be rendering correctly now. Will work on the CSS issues now.

2024-03-06 17:57 UTC, haarchri commented on content/reference/spaceapi/yaml/sharedsecretstore.yaml
> +apiVersion: spaces.upbound.io/v1beta1
i wonder what these files are - this is not a real CRD - so how you generate these files ?

2024-03-06 17:57 UTC, haarchri commented on content/reference/spaceapi/yaml/sharedsecret.yaml
> +apiVersion: spaces.upbound.io/v1beta1
i wonder what these files are - this is not a real CRD - so how you generate these files ?

2024-03-06 17:57 UTC, haarchri commented on content/reference/spaceapi/yaml/controlplane.yaml
> +apiVersion: spaces.upbound.io/v1beta1
i wonder what these files are - this is not a real CRD - so how you generate these files ?

2024-03-06 18:04 UTC, cwilhit commented
In light mode, the connective bars also render in white so they look like they're not there:

<img width="938" alt="image" src="https://github.com/upbound/docs/assets/5685031/13a232bb-ade3-4ca7-9c99-982a345bf061">

2024-03-11 17:32 UTC, plumbis approved these changes

2024-03-11 18:12 UTC, merged