update Observability with SharedTelemetryConfig
upbound/docs pull request #376
Opened 2024-04-29 11:29 UTC by lsviben

Replaces the POC Observability docs with the current [SharedTelmetryConfig](https://github.com/upbound/spaces/pull/876) approach.

2024-04-29 11:29 UTC, Upbound-CLA commented
[![CLA assistant check](https://cla.upbound.io/pull/badge/not_signed)](https://cla.upbound.io/upbound/docs?pullRequest=376) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.upbound.io/upbound/docs?pullRequest=376) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.upbound.io/check/upbound/docs?pullRequest=376) it.</sub>

2024-04-29 22:45 UTC, tr0njavolta requested changes
Some rewording/clarity

2024-04-29 22:45 UTC, tr0njavolta commented on content/spaces/observability.md
> +The `exportPipeline` field specifies the pipelines that the control planes use to send telemetry data to the exporters. The `metrics` and `traces` fields specify the names of the pipelines that the c
```suggestion
The `exportPipeline` field specifies the control plane pipelines that send telemetry data to the exporters. The `metrics` and `traces` fields specify the names of the pipelines the control planes use to send metrics and traces, respectively. The names of the pipelines correspond to the `exporters` in the OpenTelemetry Collector [service pipeline configuration](https://opentelemetry.io/docs/collector/configuration/#pipelines).
```

2024-04-29 22:45 UTC, tr0njavolta commented on content/spaces/observability.md
> +- `datadog` (check [docs](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/README.md) for configuration details)
```suggestion
- `datadog` (review the OpenTelemetry [documentation](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/README.md) for configuration details)
```

2024-04-29 22:45 UTC, tr0njavolta commented on content/spaces/observability.md
> +- `otelhttp` (used by New Relic among others, check [docs](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-set-up-your-app/
```suggestion
- `otelhttp` (used by New Relic among others, review the New Relic [documentation](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/opentelemetry-set-up-your-app/) for configuration details)
```

2024-04-29 22:45 UTC, tr0njavolta commented on content/spaces/observability.md
> +- `PROVISIONED` shows the number of control planes that successfully provisioned the OpenTelemetry Collector, and the OpenTelemetry Collector is running.
```suggestion
- `PROVISIONED` shows the provisioned and running OpenTelemetry Collectors on each control plane.
```

2024-04-29 22:45 UTC, tr0njavolta commented on content/spaces/observability.md
> +To get more data, we can check the resource status, in which we can see the names of the control planes that were selected and provisioned:
```suggestion
To return the names of control planes selected and provisioned, review the resource status:
```

2024-04-29 22:45 UTC, tr0njavolta commented on content/spaces/observability.md
> +If a conflict or another issue occurs, the failed control planes status will show the failure conditions:
```suggestion
If a conflict or another issue occurs, the failed control planes status returns the failure conditions:
```

2024-04-29 22:45 UTC, tr0njavolta commented on content/spaces/observability.md
> +Upbound marks the control plane as provisioned only if the OpenTelemetry Collector is successfully deployed and running. There could be a delay in the status update if the OpenTelemetry Collector is
```suggestion
Upbound marks the control plane as provisioned only if the OpenTelemetry Collector is deployed and running. There could be a delay in the status update if the OpenTelemetry Collector is currently deploying:
```

2024-04-29 22:45 UTC, tr0njavolta commented on content/spaces/observability.md
>  This feature requires the [OpenTelemetry Operator](https://opentelemetry.io/docs/kubernetes/operator/) to be installed on the Space cluster. Install this now if you haven't already:
```suggestion
This feature requires the [OpenTelemetry Operator](https://opentelemetry.io/docs/kubernetes/operator/) on the Space cluster. Install this now if you haven't already:
```

2024-04-30 12:16 UTC, lsviben commented
> Some rewording/clarity

Thanks @tr0njavolta ! Incorporated your suggestions

2024-04-30 16:12 UTC, tr0njavolta approved these changes

2024-04-30 17:42 UTC, merged